<?php

return [
    'programs' => [
        [
            'id' => 1,
            'code' => 'en',
            'name' => 'English',
            'title' => 'English Mastery',
            'description' => 'Build practical fluency for school, work, and international exams.',
            'full_description' => 'Master English through structured levels, guided speaking practice, and exam-oriented coaching. Learners can focus on conversation, academic writing, or certification preparation based on their goals.',
            'flag_url' => 'https://flagcdn.com/w80/gb.png',
            'sort_order' => 1,
            'is_active' => true,
            'certifications' => [
                ['name' => 'Cambridge', 'exams' => ['KET', 'PET', 'FCE', 'CAE', 'CPE']],
                ['name' => 'IELTS', 'exams' => ['Academic', 'General Training']],
                ['name' => 'TOEFL', 'exams' => ['iBT']],
            ],
        ],
        [
            'id' => 2,
            'code' => 'es',
            'name' => 'Spanish',
            'title' => 'Spanish Immersion',
            'description' => 'Progress through real-life communication and DELE-focused training.',
            'full_description' => 'Develop confident Spanish communication with balanced grammar, speaking, and listening modules. Tracks are available for travel, academic use, and official certification pathways.',
            'flag_url' => 'https://flagcdn.com/w80/es.png',
            'sort_order' => 2,
            'is_active' => true,
            'certifications' => [
                ['name' => 'DELE', 'exams' => ['A1', 'A2', 'B1', 'B2', 'C1', 'C2']],
                ['name' => 'SIELE', 'exams' => ['SIELE Global']],
            ],
        ],
        [
            'id' => 3,
            'code' => 'fr',
            'name' => 'French',
            'title' => 'French Excellence',
            'description' => 'Learn French for study, mobility, and professional communication.',
            'full_description' => 'Our French pathway combines communication practice with exam preparation for learners targeting study-abroad or career opportunities in francophone environments.',
            'flag_url' => 'https://flagcdn.com/w80/fr.png',
            'sort_order' => 3,
            'is_active' => true,
            'certifications' => [
                ['name' => 'DELF', 'exams' => ['A1', 'A2', 'B1', 'B2']],
                ['name' => 'DALF', 'exams' => ['C1', 'C2']],
                ['name' => 'TCF', 'exams' => ['Tout Public', 'DAP']],
            ],
        ],
        [
            'id' => 4,
            'code' => 'de',
            'name' => 'German',
            'title' => 'German Precision',
            'description' => 'Structured training for technical, academic, and daily communication.',
            'full_description' => 'Learn German with clear progression from foundations to advanced proficiency. Programs include practical communication and exam support for learners targeting German-speaking institutions.',
            'flag_url' => 'https://flagcdn.com/w80/de.png',
            'sort_order' => 4,
            'is_active' => true,
            'certifications' => [
                ['name' => 'Goethe', 'exams' => ['A1', 'A2', 'B1', 'B2', 'C1', 'C2']],
                ['name' => 'TestDaF', 'exams' => ['Academic']],
            ],
        ],
        [
            'id' => 5,
            'code' => 'it',
            'name' => 'Italian',
            'title' => 'Italian Pathway',
            'description' => 'Develop fluent Italian through conversation-first classroom practice.',
            'full_description' => 'This track supports learners interested in Italian language for culture, study, or relocation, with progressive speaking labs and guided grammar mastery.',
            'flag_url' => 'https://flagcdn.com/w80/it.png',
            'sort_order' => 5,
            'is_active' => true,
            'certifications' => [
                ['name' => 'CELI', 'exams' => ['A1', 'A2', 'B1', 'B2', 'C1', 'C2']],
                ['name' => 'PLIDA', 'exams' => ['A1', 'A2', 'B1', 'B2', 'C1', 'C2']],
            ],
        ],
        [
            'id' => 6,
            'code' => 'pt',
            'name' => 'Portuguese',
            'title' => 'Portuguese Track',
            'description' => 'Prepare for communication in Lusophone academic and business settings.',
            'full_description' => 'Build Portuguese fluency with practical scenarios, cultural context, and exam-ready guidance for both European and Brazilian usage contexts.',
            'flag_url' => 'https://flagcdn.com/w80/pt.png',
            'sort_order' => 6,
            'is_active' => true,
            'certifications' => [
                ['name' => 'CAPLE', 'exams' => ['A1', 'A2', 'B1', 'B2', 'C1', 'C2']],
                ['name' => 'CELPE-BRAS', 'exams' => ['Brazilian Portuguese']],
            ],
        ],
        [
            'id' => 7,
            'code' => 'ja',
            'name' => 'Japanese',
            'title' => 'Japanese Foundations',
            'description' => 'Step-by-step progress from script basics to advanced communication.',
            'full_description' => 'Learn Hiragana, Katakana, and Kanji in a structured progression, with speaking practice and JLPT-aligned support for students seeking official certification.',
            'flag_url' => 'https://flagcdn.com/w80/jp.png',
            'sort_order' => 7,
            'is_active' => true,
            'certifications' => [
                ['name' => 'JLPT', 'exams' => ['N5', 'N4', 'N3', 'N2', 'N1']],
                ['name' => 'J.TEST', 'exams' => ['Standard Track']],
            ],
        ],
    ],
];
